print("===================================")
print("Jenkins CI/CD Test Successful!")
print("Hello from Python")
print("after 2 build")
print("POLL scm test")
print("testing post build mail notification by creating error)
print("===================================")
